### ISSUE TITLE
IP 비식별화

### ISSUE THREAD

**Issue by unhochoi** [kookmin-sw/capstone-2020-7#16]
#14 의 구현 사항
feature/web 커밋시 setting.py의 IP 노출 안되도록 해야함

**Comment by hahooon** [comment]
ALLOWD_HOST 를 아예 삭제하면 사용자들이 오류가 나도 어떤식으로 고쳐야하는지 모를것 같습니다
따라서 IP부분에 ALLOWED_HOST = ['INPUT_YOUR_IP'] 라고 고치는게 사용자들한테 더 좋을것 같아요.
