### ISSUE TITLE
web_front_초안

### ISSUE THREAD

**Issue by HyeonIn** [kookmin-sw/capstone-2020-7#2]
![KakaoTalk_20200405_164457420](https://user-images.githubusercontent.com/28581435/78469533-179c3b00-775d-11ea-97c7-fd2794119da2.png)
내용에 추가해야 할 부분이나 보완해야 할 점 있으시면 얘기해주세요

**Comment by hahooon** [comment]
- 키바나를 임베딩하여 구현완료
