### ISSUE TITLE
Kibana dashboard 구현

### ISSUE THREAD

**Issue by unhochoi** [kookmin-sw/capstone-2020-7#33]
1. 다양한 Kibana dashboard를 구현
2. 구현 방법 및 내용은 README.md에 마크다운 형식으로 기술

**Comment by hyoonseo159357** [comment]
![image](https://user-images.githubusercontent.com/50091802/80099893-292d7180-85aa-11ea-9f5f-600caa4c93ca.png)

![image](https://user-images.githubusercontent.com/50091802/80099908-2e8abc00-85aa-11ea-83f8-f94f5e90c8b4.png)

![image](https://user-images.githubusercontent.com/50091802/80099945-3b0f1480-85aa-11ea-820c-ee898839801c.png)

![image](https://user-images.githubusercontent.com/50091802/80099979-45c9a980-85aa-11ea-82e0-b64cf2a2336f.png)

**Comment by hahooon** [comment]
중간발표까지의 마일스톤으로 인해 close하겠습니다.
