### ISSUE TITLE
ELK 실행 방법 문서화

### ISSUE THREAD

**Issue by HyeonIn** [kookmin-sw/capstone-2020-7#45]
문서화 내용

1. 실행 방법
2. 백그라운드 실행 방법
3. 주의 사항

**Comment by HyeonIn** [comment]
문서화는 repository에 README로 작성할 것임

**Comment by HyeonIn** [comment]
실행 방법 문서화 완료, 주의 사항 및 마무리 작업

**Comment by hahooon** [comment]
하면서 오류났던점, 어려웠던 점들도 같이 작성해주시면 좋을거같아요.
