### ISSUE TITLE
중간 자문평가 제출물

### ISSUE THREAD

**Issue by hyoonseo159357** [kookmin-sw/capstone-2020-7#8]
## 중간 자문평가 제출물 

- 중간 평가 보고서(PDF)
- 시연 동영상 
- 수행계획서 수정본(PDF) 
- 팀별 사이트 내용(md화일) -제대로 꾸미기- abstract 필수
- 발표자료

**Comment by hahooon** [comment]
- 중간 평가 보고서 (완료)
- 시연 동영상 (완료)
- 수행계획서 수정본 (완료)
- 팀별 사이트 내용 (완료)
- 발표자료 (완료)
